// This file is automatically generated. DO NOT EDIT, all your changes would be lost.
import 'package:chatapp_firebase/shared/constants.dart';
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      // case TargetPlatform.macOS:
      //   return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKTzhmfmCN_o8Y3C3zoyXAyw770KfPZLU',
    appId: '1:566905350820:web:5f4cdca0dcf5756093d431',
    messagingSenderId: '566905350820',
    projectId: 'fir-chatapp-ef231',
    authDomain: 'fir-chatapp-ef231.firebaseapp.com',
    storageBucket: 'fir-chatapp-ef231.appspot.com',
    measurementId: 'G-WQ6N9JF9PL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhRu7Sf2aKoWgXW4zJ5FNUP3fKlVJqffg',
    appId: '1:566905350820:android:f8dc69af083e82fa93d431',
    messagingSenderId: '566905350820',
    projectId: 'fir-chatapp-ef231',
    storageBucket: 'fir-chatapp-ef231.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_IOS_API_KEY',
    appId: 'YOUR_IOS_APP_ID',
    messagingSenderId: 'YOUR_IOS_MESSAGING_SENDER_ID',
    projectId: 'YOUR_IOS_PROJECT_ID',
    storageBucket: 'YOUR_IOS_STORAGE_BUCKET',
    iosClientId: 'YOUR_IOS_CLIENT_ID',
    iosBundleId: 'YOUR_IOS_BUNDLE_ID',
  );

  // static const FirebaseOptions macos = FirebaseOptions(
  //   apiKey: 'YOUR_MACOS_API_KEY',
  //   appId: 'YOUR_MACOS_APP_ID',
  //   messagingSenderId: 'YOUR_MACOS_MESSAGING_SENDER_ID',
  //   projectId: 'YOUR_MACOS_PROJECT_ID',
  //   storageBucket: 'YOUR_MACOS_STORAGE_BUCKET',
  //   iosClientId: 'YOUR_MACOS_CLIENT_ID',
  //   iosBundleId: 'YOUR_MACOS_BUNDLE_ID',
  // );
}
